import requests

# sending a GET request (we expect to get { "status" : "OK" })
print("---Get Request---")
response = requests.get("http://localhost:8000/api/v1/status")
print("Response Code:")
print(response)
print("-----------------")
print("Response Content:")
print(response.text)
print("\n\n")

# sending a POST request changing the status to 'not OK'(we expect to get { "status" : "not OK" })
print("---POST Request--")
response = requests.post("http://localhost:8000/api/v1/status", json={'status':'not OK'})
print("Response Code:")
print(response)
print("-----------------")
print("Response Content:")
print(response.text)
print("\n\n")

# sending a GET request (we expect to get { "status" : "not OK" })
print("---Get Request---")
response = requests.get("http://localhost:8000/api/v1/status")
print("Response Code:")
print(response)
print("-----------------")
print("Response Content:")
print(response.text)
print("\n\n")

# sending a POST request changing the status to 'not OK'(we expect to get { "status" : "OK" })
print("---POST Request--")
response = requests.post("http://localhost:8000/api/v1/status", json={'status':'OK'})
print("Response Code:")
print(response)
print("-----------------")
print("Response Content:")
print(response.text)
print("\n\n")

# sending a GET request (we expect to get { "status" : "OK" })
print("---Get Request---")
response = requests.get("http://localhost:8000/api/v1/status")
print("Response Code:")
print(response)
print("-----------------")
print("Response Content:")
print(response.text)
print("\n\n")